name: Run Python script
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run script
      run: python test.py
    - name: Docker Testing
      run: docker run hello-world
    - name: push to docker hub
      uses: docker/build-push-action@v4.0.0
      with:
        username: ${{secrets.}}
        password: ${{secrets.}}
        repository: docker push praveenece443/devops-project-001
        tag_with_ref: true
      
      

